AUTH_URL = "https://sargamjodhamalschool.github.io/Sargammusic/";
TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlrZXkiOiI3YjRlNjVmMy1kMGE0LTQ5ZWQtOTUzYy0yYTkzYmY3Njg1ZDQiLCJwZXJtaXNzaW9ucyI6WyJhbGxvd19qb2luIl0sImlhdCI6MTY5NTczNTM1MCwiZXhwIjoxNjk1ODIxNzUwfQ.XJGHy0fAjS6kpOpK5kYXFHL3p1qb5iV2Shj9AUKZed0"
